### ISSUE TITLE
Chat screen rotates and disappears

### ISSUE THREAD

**Issue by Fratm** [relamptk/vr-streaming-overlay#1]
Had something weird happen last ngiht.  in this vod https://www.twitch.tv/videos/398258818 at 33:33 I was teleporting aruond my vrhome home, and lost the chat overlay.. Seems it rotated so much that it just disappeared, which makes no sense, since it should not have rotated at all.

**Comment by beniwtv** [comment]
I've noticed this myself in some cases - it appears some games reset something which make the overlay's rotation being off. The reason if disappeared is that SteamVR will hide the overlay if it's rotated in a way you can't look at it anyway.

Will look into it in the next bug hunt :)
