### ISSUE TITLE
client name already exists please try again

### ISSUE THREAD

**Issue by sparker256** [relamptk/vr-streaming-overlay#10]
When I try to follow the instructions for Add connection for Twitch I get this error. I am using 0.0.3-alpha

![VR_Overlay](https://user-images.githubusercontent.com/1274225/78811014-2ff79a00-7997-11ea-8b3f-52796a2cac8d.jpg)

**Comment by beniwtv** [comment]
That is because Twitch will not allow the same name for multiple API applications. The name has to be something unique, the name in the instructions was just an example :)

Will reword the instructions to make this more clear.

**Comment by sparker256** [comment]
We are good
