### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by mnivoliez** [relamptk/vr-streaming-overlay#12]
Hello, I have tried to connect twitch but the
![image](https://user-images.githubusercontent.com/2060929/82739653-864f4b00-9d41-11ea-8dd3-623014f8794e.png)

I followed the exact steps describe and still can't connect the app.

After investigating a little, the field to enter the client ID is not visible

**Comment by beniwtv** [comment]
Twitch recently changed some stuff around, so the binary release of the overlay will currently not work. 
You can currently use the GIT master version where this is fixed (run it directly from within Godot Editor) for now.

A new release is planned shortly.

**Comment by Patola** [comment]
Hi, I just did that -- ran the project via ~/.steam/ubuntu12_32/steam-runtime/run.sh godot and then run your project, and it didn't work (using on Archlinux):
[2:33] [2567] [patola@risadinha vr-streaming-overlay]% git status
On branch master
Your branch is up to date with 'origin/master'.

The client ID field appears and the token appear below and I enter exactly what I got from https://dev.twitch.tv/console/apps/(clientid), but it does not work:

![godot-screenshot](https://user-images.githubusercontent.com/2991620/119282172-eae50480-bc38-11eb-94bf-e3578b175077.png)

**Comment by Patola** [comment]
...never mind, I was still using the previous version instructions, which used http://localhost for the redirect URL. I started the whole process and it worked now.

**Comment by beniwtv** [comment]
Nice! Real live is sucking up all my time, hopefully I can get a fixed release out soon! (Also with some features)
