### ISSUE TITLE
Feature Request: Simplify connection to twitch

### ISSUE THREAD

**Issue by merspieler** [relamptk/vr-streaming-overlay#18]
I'd like to see a simplified connection to twitch, like streamer.bot for example does, just click the button, a browser tab opens, you click authorized and it all works.

(I've had no success, with the described method while streamer.bot worked flawless.....)

**Comment by beniwtv** [comment]
That's not possible for the overlay, as I don't run a server/website. 
Keeping the client ID save somewhere in the code is not possible, so then it could be extracted and used as phishing attack against users.

What issues did you have with the method? Maybe I can help there :)

**Comment by merspieler** [comment]
The required 2FA for getting the key.

**Comment by merspieler** [comment]
another option is to use irc, which can be used without 2FA..
