### ISSUE TITLE
Help: connecting.

### ISSUE THREAD

**Issue by merspieler** [relamptk/vr-streaming-overlay#19]
I've finally managed to get past the 2FA requirement and followed the steps to connect to twitch.

At first I had to add a second OAuth Redirect URL to the application for https://twitchapps.com/tokengen to spit me out the token.

But now, if I enter the token I get it says "this token didn't work! - Client ID is missing"

And I can't figure in which format I've to to add the client ID to it, what ever I try, I get "Invalid OAuth token"...

Assuming my id is
`12345678`
and my token is
`abcdef`
How would the oauth token need to look like?

**Comment by beniwtv** [comment]
The ID is what you get when you create your application on the Twitch developer website, and there is a field in the overlay settings you have to paste it into

**Comment by merspieler** [comment]
thanks for the quick reply

I don't see an ID field anywhere.

What I did:
* Go to connections
* follow the steps there
* paste the token I've gotten

in overlays I've got one overlay with twitch widget, there I can't select a connection yet, as the previous step failed.

what am I overlooking?

**Comment by beniwtv** [comment]
Which version are you currently using? The ones under the "release" tab are currently too old, you need to download this repo and run it directly from Godot.

(I'm basically waiting for Godot 4 and OpenXR to be done to make a new release, with some additional new stuff)

**Comment by merspieler** [comment]
oh, I've been running the latest release...
I guess there we've got the issue... I'll see, if I get this to build.

**Comment by merspieler** [comment]
okay, so I've successfully built it and connecting works now but at the bottom I see now an error message which wasn't there with the old release version:
> Could not initialize OpenVR -> check console output

console says this:
```
Godot Engine v3.4.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon Vega Frontier Edition (VEGA10, DRM 3.40.0, 5.10.98, LLVM 13.0.0)
OpenGL ES Batching: ON
 
Found widget: Twitch chat (twitchchat.gd)
Usage count increased to 2
OpenVR: initialising OpenVR context

Application in overlay mode.
Main OpenVR interface has been initialized
Main render models interface has been initialized.
Exec path: /nix/store/132wmmmsx63nyy530y7y1jf7ndmkqh9b-vroverlay-62148d79066cbecec83c32a252ef8cec5a4b0d14/share/vroverlay
Failed to find action file
Usage count decreased to 1
```

I've tried the suggested ways 1 and 3 from the readmes Linux notes but without success...

**Comment by beniwtv** [comment]
There's the actions folder here: https://github.com/beniwtv/vr-streaming-overlay/tree/master/addons/godot-openvr/actions
The action folder needs to be alongside from where your executing the overlay.

**Comment by merspieler** [comment]
Now it tells me, I can put on the headset but I can't see anything in VR.

the console spams
`OpenVR could not set texture for overlay: 24VROverlayError_InvalidTexture`

**Comment by beniwtv** [comment]
Hmm, that's one I haven't seen so far - what's your GPU/driver?

**Comment by merspieler** [comment]
GPU: AMD Radeon Vega Frontier Edition
Driver amdgpu Version 21.2.6, if I see this correctly:
```
[nix-shell:~]$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Vega Frontier Edition (VEGA10, DRM 3.40.0, 5.10.98, LLVM 13.0.0) (0x6863)
    Version: 21.2.6
    Accelerated: yes
    Video memory: 16384MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 14789 MB, largest block: 14789 MB
    VBO free aux. memory - total: 16238 MB, largest block: 16238 MB
    Texture free memory - total: 14789 MB, largest block: 14789 MB
    Texture free aux. memory - total: 16238 MB, largest block: 16238 MB
    Renderbuffer free memory - total: 14789 MB, largest block: 14789 MB
    Renderbuffer free aux. memory - total: 16238 MB, largest block: 16238 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 16384 MB
    Total available memory: 32752 MB
    Currently available dedicated video memory: 14789 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Vega Frontier Edition (VEGA10, DRM 3.40.0, 5.10.98, LLVM 13.0.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by beniwtv** [comment]
That all looks good, wonder why SteamVR is thinking that the OpenGL texture Godot gives it is not valid :thinking:

**Comment by beniwtv** [comment]
Maybe worth a try: could you try replacing the OpenVR .so files with the current ones from here? https://github.com/ValveSoftware/openvr/tree/master/bin/linux64
