### ISSUE TITLE
Feature Request - Make chat invisible until needed, pop up maybe?

### ISSUE THREAD

**Issue by Fratm** [relamptk/vr-streaming-overlay#4]
Not sure how this would be done, but I saw a streamer once using something like this where they would twist there wrist and the chat window would pop up attached to there wrist.  Then when they were done reading, the just twisted there wrist back.. Looked cool, and it keeps the chat window out of the way until needed.

**Comment by beniwtv** [comment]
Yes, I want to implement something like this once the absolute modes handles like I want it to. The overlay can already be attached to hands - so shouldn't be too difficult

**Comment by beniwtv** [comment]
Implemented by fd325f9ef8b3b941c751742f1b9fd5681c9c3ce0
